### ISSUE TITLE
Avoiding loading whole symfony framework for symfony/messenger tests 

### ISSUE THREAD

**Issue by tigitz** [mmasiukevich/performance-comparison#11]
Hello, great job setting up the benchmark, must have been quite a time consuming task so thanks for doing it.

I realised when checking the code that you're bootstrapping the whole symfony framework which I believe is not really reliable for test comparison since the time taken to process the message also includes the orm and so on.

I would suggest to create a test similar to the pure php one and just using the components for the consumer / provider.

https://symfony.com/doc/current/components/messenger.html#transports

**Comment by mmasiukevich** [comment]
Greetings.
Bootstrap time hasn't  effect on runtime. The test doesn't use ORM, only DBAL.
Physical removal of dependencies has no effect on time. It's just that the messenger itself performs a lot of non-optimal and useless actions. Plus, amqp-ext itself is very slow and buggy.

As for the tests "in pure form", then there is a PHP implementation nearby, with practically no dependencies (amqp-ext, json, pdo-pgsql)

**Comment by mmasiukevich** [comment]
for example: https://blackfire.io/profiles/d73274c5-1c2b-4937-9377-f11903ab60e8/graph

But ... you always can send a merge request and we will check the perfomance with your fixes :)
I assure you, if the result changes, it isn't significant
